Repository SSAGESLabs/PySAGES, pull requests merged in 2022-06, with the labels that each got.

#141 add missing metad doc
  docs/source/module-pysages-methods-metad.rst
  docs/source/module-pysages-methods-utils.rst
  docs/source/module-pysages-methods.rst
  pysages/methods/metad.py
  pysages/methods/utils.py
Labels: documentation

#139 Add some details to making working with PySAGES easier
  pysages/backends/core.py
  pysages/colvars/core.py
  pysages/methods/core.py
  pysages/methods/umbrella_integration.py
Labels: bug

#143 Auto spell check documentation
  .github/workflows/ci.yml
  docs/Makefile
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/pysages_wordlist.txt
  pysages/colvars/coordinates.py
  pysages/colvars/core.py
  pysages/colvars/shape.py
  pysages/methods/__init__.py
  pysages/methods/abf.py
  pysages/methods/core.py
  pysages/methods/ffs.py
  pysages/methods/harmonic_bias.py
  pysages/methods/metad.py
  pysages/methods/umbrella_integration.py
  pysages/methods/utils.py
Labels: documentation

#140 Add a post function to run after `backend.run` to finish up or store final results
  examples/hoomd-blue/umbrella_integration/integration.py
  pysages/methods/core.py
  pysages/methods/umbrella_integration.py
Labels: enhancement

#147 Ensure all sampling methods are picklable
  pysages/grids.py
  pysages/methods/abf.py
  pysages/methods/ann.py
  pysages/methods/core.py
  pysages/methods/ffs.py
  pysages/methods/funn.py
  pysages/methods/harmonic_bias.py
  pysages/methods/metad.py
  tests/test_pickle.py
Labels: needs tests, parallelization

#148 Nicer documentation landing page
  .github/workflows/ci.yml
  README.md
  docs/Makefile
  docs/source/index.rst
  docs/source/module-pysages-colvars.rst
  docs/source/module-pysages-methods.rst
  docs/source/package-pysages.rst
  docs/source/pysages_wordlist.txt
Labels: documentation
