Repository SSAGESLabs/PySAGES, pull requests merged in 2022-08, with the labels that each got.

#196 use eigh instead of eigvals
  pysages/colvars/shape.py
Labels: bug, collective variables

#193 NaCl example with metadynamics and OpenMM
  examples/inputs/nacl/nacl-explicit.pdb
  examples/openmm/metad/nacl/Metadynamics_NaCl.ipynb
  examples/openmm/metad/nacl/Metadynamics_NaCl.md
  examples/openmm/metad/nacl/nacl-explicit.pdb
  examples/openmm/metad/nacl/nacl.py
Labels: examples

#194 Flexibility in choosing which orientation the acyclindricity is calcualted
  docs/source/pysages_wordlist.txt
  pysages/colvars/shape.py
Labels: collective variables

#201 Enable meaningful post action triggers for OpenMM
  examples/openmm/abf/alanine-dipeptide_openmm.py
  examples/openmm/umbrella_integration/integration.py
  pysages/methods/core.py
  pysages/methods/ffs.py
Labels: backends
